spring:
  datasource:
    url: jdbc:mysql://localhost:3306/walab_camp_board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: kds43965@@
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop